name: Update Longhorn Repository Branch Image Tags

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch, ex: v1.7.x"
        required: true
      tag:
        description: "Tag, ex: v1.7.x-head"
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}

    steps:
    - name: Setup Git
      run: |
        gh auth setup-git

    - uses: actions/checkout@v4

    - name: Update repo branch image tags
      run: ./scripts/update-repo-branch-image-tags.sh ${{ inputs.branch }} ${{ inputs.tag }}
